version: '3'
services:
  db:
    image: postgres
    container_name: postgres
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - pg-db-fastapi:/var/lib/postgresql/data
volumes:
  pg-db-fastapi:
    name: 'pg-db-fastapi'
    # external: true