version: '3'
services:
  fast-app:
    build: .
    container_name: fast-app
    image: fast-app:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    volumes:
      - pg-db-fastapi:/var/lib/postgresql/data
volumes:
  pg-db-fastapi:
    name: 'pg-db-fastapi'
    # external: true